### ISSUE TITLE
TSDLC - Automate WhiteSource scan

### ISSUE THREAD

**Issue by jeffdoolittle** [trimble-oss/modus#208]
Tools for automation:

 * [Mend (formerly WhiteSource)](https://www.mend.io/)
 * [SonarQube](https://www.sonarqube.org/)
 * If we are moving to AWS/Azure - Crowdstrike
 * TSDLC Team takes care of configuring and scheduling below scans,
     * Rapid 7
     * Tenable

Note:
To run a unified agent jar from WhiteSource - use GitHub Actions.

**Comment by msankaran0712** [comment]
Received communicatin from DevOps team that we can use Trimble Connect's Github action for the Whitesource scan and also look at their available SonarQube action for dotnet and talk to their team.

**Comment by msankaran0712** [comment]
https://github.com/Trimble-Connect/tc-actions/tree/main/whitesource-scanner

https://github.com/Trimble-Connect/tc-actions/tree/main/sonar-scan-dotnet

**Comment by msankaran0712** [comment]
https://github.com/trimble-oss/modus-react-bootstrap/issues/155
https://github.com/trimble-oss/website-modus.trimble.com/issues/232
https://github.com/trimble-oss/website-modus-bootstrap.trimble.com/issues/211
