### ISSUE TITLE
Cookie Banner Guidelines

### ISSUE THREAD

**Issue by jeffdoolittle** [trimble-oss/modus#210]
[OneTrust Cookie banners](https://app.onetrust.com/auth/login) are commonly used on Trimble websites for GDPR and California Consumer Privacy Act (CCPA) compliance.

The default banners styling is not Modus compliant (colors/fonts/sizes etc). We should  provide guidelines on styles to use.

**Comment by enowak1031** [comment]
@coliff Can we delete this?

**Comment by coliff** [comment]
I'll delete it for now and if we need to we can re-add in the future. (reason being - I can't remove the `priority:high` tag)
