### ISSUE TITLE
Date Picker Designs & Review

### ISSUE THREAD

**Issue by jeffdoolittle** [trimble-oss/modus#225]
As a user of the design system, I want to have a date picker available, so that I can provide a consistent experience to our users.

**Comment by enowak1031** [comment]
Submission from MAPS

**Comment by soniakaukonen** [comment]
Submission also by Dafnee Zambrano from E-Builder: https://docs.google.com/document/d/1ftygiyzpEWZ-4fqlZsRjX5EPYMB_OcmTNtAP6s9Nblo/edit#heading=h.zgiv6dutoq8l @egunther39 @enowak1031 for discussion.
