### ISSUE TITLE
Skeleton / Placeholder Guidelines

### ISSUE THREAD

**Issue by jeffdoolittle** [trimble-oss/modus#231]
As a user of the design system, I want to have the option to use a skeleton in my application, so that it helps the user with loading times.

- https://getbootstrap.com/docs/5.1/components/placeholders/

**Comment by coliff** [comment]
Modus Bootstrap 2 Preview:
https://modus-bootstrap.netlify.app/docs/5.3/components/placeholders/

**Comment by msankaran0712** [comment]
Closing as this is a duplicate of https://github.com/trimble-oss/modus/issues/432
