### ISSUE TITLE
File Upload Dropzone for Dark Mode in XD

### ISSUE THREAD

**Issue by enowak1031** [trimble-oss/modus#306]
As a designer working in Adobe XD, I want to have the File Upload Dropzone available in the XD UI Kit, so I can build my interfaces.

**Comment by egunther39** [comment]
Added Dropzone to dark mode XD.

![image](https://user-images.githubusercontent.com/98049598/183734899-79c99d99-2329-478b-b7c8-12e5ec771b45.png)
