### ISSUE TITLE
Pagination Broken Down into Smaller Elements / Enhancements

### ISSUE THREAD

**Issue by soniakaukonen** [trimble-oss/modus#341]
See survey findings https://docs.google.com/presentation/d/1ekou3J2SY6XXj1asQVgnNJT4UXDhz6hAR_bmSnPmEbc/edit#slide=id.g18d0eacc774_0_60

Pattern submission Carlos Rodriguez:

- [ ] prev next text links in addition to < > 
- [ ] dropdown for limitation of visible pages between < > 

Accessibility tiger team recommendations: https://docs.google.com/document/d/1WOCMpMuiI-H050w9ZQQr7PjOabioaZBEr1Y9aNZwNG8/edit#

- [ ] Consider providing only accessible component version
- [ ] Harmonize Adobe XD and Figma UI kits, correct color code errors
- [ ] Check screen reader behavior with visual separators

**Comment by enowak1031** [comment]
@soniakaukonen I thought we got this done already. Is that right?
