### ISSUE TITLE
Tab Broken Down into smaller Elements

### ISSUE THREAD

**Issue by soniakaukonen** [trimble-oss/modus#343]
Enable the designer to decide about the amount of tabs and allow text style definition, e.g. all caps. Compare to XD too. See survey results https://docs.google.com/presentation/d/1ekou3J2SY6XXj1asQVgnNJT4UXDhz6hAR_bmSnPmEbc/edit#slide=id.g18d0eacc774_0_60

**Comment by enowak1031** [comment]
Related to https://github.com/trimble-oss/modus/issues/480
