### ISSUE TITLE
Clear button added to autocomplete input field

### ISSUE THREAD

**Issue by soniakaukonen** [trimble-oss/modus#346]
https://docs.google.com/presentation/d/1ekou3J2SY6XXj1asQVgnNJT4UXDhz6hAR_bmSnPmEbc/edit#slide=id.g18d0eacc774_0_71

**Comment by enowak1031** [comment]
@soniakaukonen This requires clarification

**Comment by soniakaukonen** [comment]
Figma analytics result, resolved during Figma vs. style guide review and Icon renewal on Figma. Issue solved, can be closed/duplicate.
