### ISSUE TITLE
Review & Update Mobile Figma UI Kit

### ISSUE THREAD

**Issue by enowak1031** [trimble-oss/modus#353]

**Comment by soniakaukonen** [comment]
Wed-Friday

[ ] Get to know color palette, variants, components

[ ] Checking correct Trimble palette colors - are there any # color codes not Trimble or disconnected Trimble colors?
[ ] Making sure they have brand colors w the name
[ ] Make a list, send to Sonia


[ ] Try out boolean variant for dark mode on 2-3 different components - work in branch
badges, chips, tabs

**Comment by nbyati** [comment]
**Completed in Sprint 50:**

- [ ] [ ] Get to know color palette, variants, components
-
- [ ] [ ] Checking correct Trimble palette colors - are there any # color codes not Trimble or disconnected Trimble colors?
- [ ] [ ] Making sure they have brand colors w the name
- [ ] [ ] Make a list, send to Sonia
- [ ] [ ] Try out boolean variant for dark mode on 2-3 different components - work in branch
- Not feasible & not needed in the variants.
- [ ] [ ] badges, chips, tabs
