### ISSUE TITLE
Add Remaining Dark Mode Images for In-Field Components

### ISSUE THREAD

**Issue by enowak1031** [trimble-oss/modus#357]
- [x] Segmented Controls
- [x] Switches

- [x]  Modal (light mode is currently dark)

**Comment by enowak1031** [comment]
- [ ] Segmented Controls
- [ ] Switches

**Comment by soniakaukonen** [comment]
@coliff 

https://drive.google.com/drive/folders/1n8YUeTJkZ_X9P6qA11tjSbPpz82NSIkc dropped all three fixes named accordingly -dark and in same format (one in svg, others in png) If pngs should be replaced too let me know. I can extract svgs too. (Why do we have pngs in In-Field style guide body at all?).

**Comment by coliff** [comment]
Closing this as completed now.
