### ISSUE TITLE
New Graphics for Modus

### ISSUE THREAD

**Issue by soniakaukonen** [trimble-oss/modus#381]
New Modus illustrations needed for:

- [x] Modus homepage header  (general https://modus.trimble.com/)
- [x] Bootstrap
- [x] React

Style guide component introduction pages (dark and light mode):
- [x] Web (x2)
- [x] Mobile (x2)
- [x] In-Field (x2)
------
- [x] XR (x2) - later
- [ ] Desktop (x2) ) - later

Error page graphics:
- [x] Error pages (dark and light)

Figma file header cards: 
- [x] Web
- [x] Mobile 
- [x] In-Field 
- [x] Foundations (temp)
- [x] Iconography (temp)
------
- [x] XR - later
- [ ] Desktop   - later

**Comment by soniakaukonen** [comment]
High resolution extracted from Discord
Meeting placeholder with Cory Fri Mar 17th

**Comment by coliff** [comment]
For the new images I suggest we modify the aspect ratio to work better as Open Graph images (used when sharing on Slack and Google Chat). Right now the images crop too heavily and don't look good.
![image](https://user-images.githubusercontent.com/1212885/227558698-e4ed4506-6a21-4ead-a0a5-a0bb57025cf5.png)
Creating images in 16x9 aspect ratio would help.

**Comment by enowak1031** [comment]
![modus-main](https://user-images.githubusercontent.com/97305117/228280180-475c6d53-3152-4738-8a30-ab9a45c55b7f.png)

**Comment by enowak1031** [comment]
![bootstrap-main](https://user-images.githubusercontent.com/97305117/228366443-86282cf4-7a0f-48c2-83e5-da6f8fc4bd22.png)
![react-main](https://user-images.githubusercontent.com/97305117/228366452-394b0bd4-0c41-4f9c-bcad-29ef096d9281.png)

**Comment by enowak1031** [comment]
![modus-web](https://user-images.githubusercontent.com/97305117/228366670-f78bf733-ede7-4c07-a089-417557601f45.png)
![modus-mobile](https://user-images.githubusercontent.com/97305117/228366680-847dfc1d-e988-4edb-b762-1dd54f6ee1c2.png)
![modus-infield](https://user-images.githubusercontent.com/97305117/228366685-b970d567-7db2-4ddc-bed8-2a49a9d9591d.png)
