### ISSUE TITLE
Update all icons in Figma in the Mobile Kit

### ISSUE THREAD

**Issue by enowak1031** [trimble-oss/modus#384]

**Comment by soniakaukonen** [comment]
Fast screening, icons in components:

- [ ] Accordions - chevrons
- [ ] Alerts - alert message icons
- [ ] Autocomplete - chevrons, magnifier
- [ ] Breadcrumbs - cherron right
- [ ] Butons - magnifier
- [ ] Checkbox - tick (?)
- [ ] Content tree - chevron, tickboxes (?), folder
- [ ] Date picker - chevrons left/right, chevrons up/down, magnifier, calendar
- [ ] Dropdowns - tick on/off (?)
- [ ] Dropzone - cloud upload
- [ ] Inputs -chevrons, + - , info token
- [ ] Navbar - (hamburger) menu, bell, magnifier, apps, ?- help, drop down chevron
- [ ] Pagination - chevron left/right
- [ ] Side nav - chevron left/right, hamburger menu

Fast screening, icons in style guide screenshots:

**Comment by nbyati** [comment]
**Mobile**

- [ ] Accordions
- [ ] Buttons
- [ ] Cards (except heart icon)
- [ ] Footers (except profile icon)
- [ ] Inputs (left a comment for protocol for inline message icons)
- [ ] Lists (except for profile icon)
- [ ] Inputs (same comment from inputs)
- [ ] Navbar (except profile icon)
- [ ] Scrollbar
- [ ] Status bar
- [ ] Switches
- [ ] Tables
