### ISSUE TITLE
Mobile Figma UI kit property conflicts to solve

### ISSUE THREAD

**Issue by soniakaukonen** [trimble-oss/modus#386]
Some property names and values prevent asset re-publishing:

![Image](https://user-images.githubusercontent.com/101354258/214060661-8255e78c-4cd8-4b70-8707-62865c24b4a5.png)

![Image](https://user-images.githubusercontent.com/101354258/214060507-849522a3-84f6-48ab-a55c-8ebf7ca423a0.png)

Unused properties can be checked with the creators if still needed. Conflicts need resolving.

**Comment by nbyati** [comment]
Completed & edited!
