### ISSUE TITLE
Update the Iconography file in Figma

### ISSUE THREAD

**Issue by enowak1031** [trimble-oss/modus#395]

**Comment by soniakaukonen** [comment]
Icon portfolio has been published and available through Assets in alphabetical order! @nbyati 


Issues for old core-24 icon removal:

- [ ] Icons for + and - plain for add and remove. Do we need it? Do we want it? There is a circle with + and -
- [ ] drag handle (was = should be two columns of 3 dots (Material?)
- [ ] Checkboxes: ticked (solid, outline), empty (universal), indeterminated (boxwith dash)
- [ ] Should "Transportation" also be published on Figma?

Other minor issues:

- [ ] Image still a double (image-scene should remain)
- [ ] window-wireframe still not replaced with newer svg

@egunther39 @coliff 

All others exist and I am removing them from Iconography. Graveyard likewise.
