### ISSUE TITLE
Update component icons in Figma In-Field UI kit

### ISSUE THREAD

**Issue by soniakaukonen** [trimble-oss/modus#397]
Mathew preparing a list which requires stronger stroke for in-field, should be quite limited. This will affect the key icon set: the chevrons needed in this file.

Was hoping to finalize it along with missing componenents / dark mode. Now moved below the line. In touch with Lee.

**Comment by nbyati** [comment]
Remaining components but created new task for fixing the colored icons that have different specifications. Setting up a meeting w Mathew to discuss & problem solve.
