### ISSUE TITLE
Rename Dark Badge to High Contrast on Figma and XD. Apply style guide colors

### ISSUE THREAD

**Issue by soniakaukonen** [trimble-oss/modus#403]
Dark badge won't be maintained in dark mode. Instead:

- [x] Rename to High Contrast in light and dark mode
- [x] Apply colors in dark mode according to style guide (gray light, gray 10 text)

in 

- [x] Figma
- [x] XD

See clickup for details: https://app.clickup.com/t/8669e7r38

**Comment by egunther39** [comment]
Fixed in XD
