### ISSUE TITLE
Action Bar for Content Tree in Figma

### ISSUE THREAD

**Issue by soniakaukonen** [trimble-oss/modus#404]
https://app.clickup.com/t/8669fy3mq

and

https://github.com/trimble-oss/modus/issues/399

**Comment by nbyati** [comment]
Completed here: https://www.figma.com/file/wyfVJUHWRMkeCfdB38HFEE/branch/FYxsolNyJNvYEC0zPyiuV0/Modus---Web?node-id=5350%3A22364&t=UhLIwzAYWH8Bl2k0-1
