### ISSUE TITLE
Edit Mobile Input Fields to reflect Web inputs

### ISSUE THREAD

**Issue by nbyati** [trimble-oss/modus#408]

**Comment by nbyati** [comment]
Waiting direction on text & selected state.

**Comment by soniakaukonen** [comment]
Text final: 

Labels 12 px regular
helptext default 11 px regular, large 12 px regular

Underline selected for Web, whole outline on Mobile and In-Field (to be discussed on Feb 21st with Matthew Johns)

Helptext token gray/blue, no representation on Style Guide or XD. To be discussed on Review meeting Feb 21st.
