### ISSUE TITLE
Progress Indicator for File Upload Dropzone in Figma

### ISSUE THREAD

**Issue by enowak1031** [trimble-oss/modus#420]
Full description here: https://github.com/trimble-oss/website-modus.trimble.com/issues/450

**Comment by nbyati** [comment]
Completed https://www.figma.com/file/wyfVJUHWRMkeCfdB38HFEE/branch/FYxsolNyJNvYEC0zPyiuV0/Modus---Web?node-id=5762%3A22364&t=UhLIwzAYWH8Bl2k0-1
