### ISSUE TITLE
Add GitHub discussions for Modus

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/modus#423]
To have something like https://github.com/trimble-oss/modus-web-components/discussions/categories/q-a for the whole Modus Design system and put that link in multiple places across Modus sites.

cc/
@coliff
@enowak1031

**Comment by coliff** [comment]
Great idea. We have this setup now!
https://github.com/orgs/trimble-oss/discussions

**Comment by msankaran0712** [comment]
We need this in announcements

**Comment by msankaran0712** [comment]
@soniakaukonen to add ?

**Comment by soniakaukonen** [comment]
https://github.com/trimble-oss/website-modus.trimble.com/issues/579 form renewal

**Comment by msankaran0712** [comment]
done in https://github.com/trimble-oss/website-modus.trimble.com/issues/579
