### ISSUE TITLE
Modus Mobile - Need a separate GitHub project

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/modus#471]

**Comment by coliff** [comment]
Hi, what are the requirements for the project settings? Some things I can think of:

- Should sprint start from 1 or should we synchornize them with Modus and MWC?
- Who needs admin access?
- I assume it'll be private (initially at least?), let me know if you wanted it public
- What boards/statuses are needed?

**Comment by msankaran0712** [comment]
- I would hope to continue with the existing sprint as we did for Web components.
- Ramaraj, you and I think should have admin access
- Modus Mobile GitHub project should be Public. @enowak1031 Please correct me if am wrong.
 - Because there was no reason why it should not be public.
- Statuses - I would expect the existing status to continue but @rthanga1 can provide his thoughts
- Boards - existing board can be replicated, @rthanga1 @enowak1031 can provide some thoughts

**Comment by coliff** [comment]
I've now setup the project and the admins, workflows, sprints, status labels.

https://github.com/orgs/trimble-oss/projects/18/views/3
