### ISSUE TITLE
Date picker enhancement to accept any format

### ISSUE THREAD

**Issue by soniakaukonen** [trimble-oss/modus#486]
Submission reviewed by MoAB Aug 15. https://app.clickup.com/t/86858ewpx

More information needed.

**Comment by soniakaukonen** [comment]
Overall suggestion is to revisit date picker for better Figma component controls as well as matching web functionality with Figma component functionality.

**Comment by soniakaukonen** [comment]
@msankaran0712 to check if this is a bug.

**Comment by msankaran0712** [comment]
It is a enhancement and not a bug

**Comment by msankaran0712** [comment]
Maha to transfer the issue to web cpomponents

**Comment by msankaran0712** [comment]
Closing the issue as nothing to do in Figma and web components has a separate issue https://github.com/trimble-oss/modus-web-components/issues/1709 

cc
@soniakaukonen
