### ISSUE TITLE
Chevron padding for Pagination on Figma

### ISSUE THREAD

**Issue by jmecosta** [trimble-oss/modus#492]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-react-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-react-bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

<img width="736" alt="image" src="https://github.com/trimble-oss/modus-react-bootstrap/assets/1041352/4ef02f94-2dca-4318-8e57-000fb26960bf">

### Motivation and context

usability

**Comment by msankaran0712** [comment]
@jmecosta This will be fixed only on Styleguide, Figma and Modus Bootstrap. I have repurposed this issue to reflect the Figma changes, I hope that's okay.

**Comment by jmecosta** [comment]
Also in modus web components? That's what we will begin using as per recommendation

**Comment by msankaran0712** [comment]
@jmecosta Yes, currently Modus Web Components has its own icons and they are large enough. However, soon Modus Web Components will start using Modus Icons, which can be found at https://modus-icons.trimble.com/.

**Comment by jmecosta** [comment]
Ok clear. Thanks for the update.
